language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
install:
  - pip install .
script:  python setup.py nosetests
addons:
  apt:
    packages:
    - clamav-deamon
matrix:
  allow_failures:
    - python: "2.5"
sudo: false
